<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Error when going live with the patching</title>
    <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583</link>
    <description>hi, i did mention this in another post, now i am at home i got a problem going live with whatever tutorial or demo program or somethin i patch my own:

i will paste the red error message, i got no clue what this could be, maybe someone already had an issue like that:

! C:\Users\xxxxx\DOCUME~1\axoloti/build/xpatch.h.gch
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:190: MapViewOfFileEx: Attempt to access invalid address. 


Did I delete a file , not on purpose.

Next thing maybe i reinstall the whole software and flash the st32 on the board...

Help appreciated :)  thanks</description>
    
    <lastBuildDate>Wed, 23 Nov 2022 08:02:59 +0000</lastBuildDate>
    <category>Helpdesk</category>
    <atom:link href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@ParanormalPatroler]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/paranormalpatroler">@ParanormalPatroler</a> wrote:</p>
          <blockquote>
              <p>For me, deleting the files was not enough. Restarting the Editor was not enough. I had to restart the computer and then it worked.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/51">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/51</link>
        <pubDate>Wed, 23 Nov 2022 08:02:59 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-51</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@kale]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/kale">@kale</a> wrote:</p>
          <blockquote>
              <p>had the same problem, deleting files in documents/axoloti/build folder solved it as reported before by <a class="mention" href="/u/mtyas">@mtyas</a></p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/50">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/50</link>
        <pubDate>Fri, 08 Jan 2021 10:56:51 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-50</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@nominal Gabriel Jennings]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/nominal">@nominal</a> wrote:</p>
          <blockquote>
              <p>I just had the same issue after shutting down my PC to troubleshoot a separate unrelated (Ableton audio) issue. I don't believe I'd cleanly shut down the Axoloti patcher beforehand, but I can confirm that dropping a .old extension to the end of xpatch.h.gch resolved it. </p>

<p>A quick google search brought me right to this page, so thanks for having that posted and easy to find, TechnoBear!</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/49">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/49</link>
        <pubDate>Sat, 02 Mar 2019 05:54:38 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-49</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@soren1 soren]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/soren1">@soren1</a> wrote:</p>
          <blockquote>
              <p>same problem here.. deleting that file in documents helped, but I hope this is not something that needs to be done regularly</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/48">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/48</link>
        <pubDate>Sun, 14 Oct 2018 09:11:45 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-48</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@reaganry reaganry]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/reaganry">@reaganry</a> wrote:</p>
          <blockquote>
              <p>wow, so glad i found this thread before I started cutting the traces to IC4! I'm not sure if this was related to my overheating problem (don't plug into your computer speakers!) or just randomly concurrent...</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/47">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/47</link>
        <pubDate>Wed, 02 May 2018 20:38:18 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-47</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@KrizRoring Christian Roring]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/krizroring">@KrizRoring</a> wrote:</p>
          <blockquote>
              <p>Got the same problem today.<br>Reinstalling didn't help but in the end found the problem:</p>

<p>Windows Defender enabled a setting called: Controller folder access</p>

<p>This is enabled for the \Documents folder, which axoloti used for the live patch.<br>Disabling this option in Windows Defender&gt; Virus and Threat protection (remember to turn it on again afterusing the axoloti software) solves the error for the live patches.</p>

<p>Greetings,<br>Kriz</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/46">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/46</link>
        <pubDate>Mon, 26 Feb 2018 22:09:02 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-46</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@Enkerli Alex Enkerli]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/enkerli">@Enkerli</a> wrote:</p>
          <blockquote>
              <p>Thanks for this. Might make sense to put a sticky on this answer or document it somehow.<br>Had the same issue and deleting documents/axoloti/build/xpatch.h.gch did the trick.<br>A bit more info. Windows 10 machine. Installed the software about a month ago, played with somebody else’s Core without getting this problem.<br>Just received my own Core today. Plugged it in, updated the firmware, encountered the same problem with the first tutorial patch (01_sine_oscillator). Did a web search for MapViewOfFileEx axoloti and got to this thread. Scanned the thread, saw <a class="mention" href="/users/mtyas">@mtyas</a> mentioning the correct folder, and <a class="mention" href="/users/thetechnobear">@thetechnobear</a> confirming which file was affected. </p>

<p>Disconnected everything, deleted the xpatch file, fired up the Axoloti software, plugged the Core, and now everything sounds like it’s working.</p>

<p>Now comes the fun part of learning how to really do stuff with Axoloti.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/45">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/45</link>
        <pubDate>Thu, 18 May 2017 20:09:34 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-45</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@thetechnobear Mark Harris]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/thetechnobear">@thetechnobear</a> wrote:</p>
          <blockquote>
              <p>ok, so just got myself a windows laptop (something I'm surprised about too <img src="//community.axoloti.com/images/emoji/emoji_one/wink.png?v=3" title=":wink:" class="emoji" alt=":wink:">) and been playing with Axoloti on it (quite fun with a touchscreen, doesn't work too bad.)</p>

<p>and just encountered this error.</p>

<p>so,  I can now confirm its the precompiled header that is the issue, if you delete xpatch.h.gch then the problem is resolved. it is corrupted.</p>

<p>a quick check shows the corrupted file is the same size as the 'uncorrupted version' but has some bytes differing... now, I know that last time I used Axoloti, it was ok.<br>BUT the accompanying dependency file has the same timestamp, so it doesn't look like its been altered... quite odd.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/44">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/44</link>
        <pubDate>Fri, 31 Mar 2017 17:45:07 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-44</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@SmashedTransistors]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/smashedtransistors">@SmashedTransistors</a> wrote:</p>
          <blockquote>
              <p>Got this problem today. <br>Thanks for the tip <a class="mention" href="/users/mtyas">@mtyas</a> !</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/43">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/43</link>
        <pubDate>Tue, 28 Mar 2017 19:03:55 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-43</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@mtyas Matthew Tyas]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/mtyas">@mtyas</a> wrote:</p>
          <blockquote>
              <p>Just had this error again (hdan't had it since a long time), I just deleted the 3 files in the documents/axoloti/build folder and it works again, as usual. <br>Just thought I'd let you know</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/42">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/42</link>
        <pubDate>Fri, 13 Jan 2017 10:28:18 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-42</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@DazzlingDuke Daniel D Lindmark]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/dazzlingduke">@DazzlingDuke</a> wrote:</p>
          <blockquote>
              <p>I just experienced this. I'm running Win 10 and it just published an update and restarted my computer while the program was running. When I tried to load and compile any Axoloti patch, I would get this error. I restarted the computer and the error is gone. If you get this error, I recommend restarting your computer. Luckily it was an easy fix.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/41">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/41</link>
        <pubDate>Fri, 19 Aug 2016 15:12:55 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-41</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@thetechnobear Mark Harris]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/thetechnobear">@thetechnobear</a> wrote:</p>
          <blockquote>
              <aside class="quote" data-post="38" data-topic="583"><div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="//community.axoloti.com/user_avatar/community.axoloti.com/johannes/40/8_1.png" class="avatar">johannes:</div>
<blockquote><p>I haven't experienced this, maybe a the compiler was aborted somehow while generating the xpatch.h.gch file, but leaving a corrupt/incomplete file.</p></blockquote></aside>

<p>yeah, thats what I was wondering.... if deleting the build directory fixes it, then it sounds like a file that used across builds.<br>but even then, its odd... since the gch wont be changing, unless the firmware is updated... so how does it 'suddenly' become corrupt, if it was working before.</p>

<p>anyway, would be nice to narrow down , which file in the build directory is causing the trouble, then work out why <img src="/images/emoji/emoji_one/wink.png?v=2" title=":wink:" class="emoji" alt=":wink:"> </p>

<p>btw, if deleting xpatch.h.gch doesn't immediately fix it, i.e. build still crashes, delete one file at a time in the build directory (remembering which you deleted!) and try again... though I think its only the gch file across builds.</p>

<p>(I guess we could have a 'secret key' e.g. pressing ALT whilst going live, which could perform a make clean, then make.)</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/40">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/40</link>
        <pubDate>Tue, 31 May 2016 23:25:18 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-40</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@philoop]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/philoop">@philoop</a> wrote:</p>
          <blockquote>
              <p>hmmmm <img src="/images/emoji/emoji_one/kissing_heart.png?v=2" title=":kissing_heart:" class="emoji" alt=":kissing_heart:"><a class="mention" href="/users/johannes">@johannes</a> <br> I'll try and see if there is any pattern when I continue tomorrow.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/39">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/39</link>
        <pubDate>Tue, 31 May 2016 23:11:44 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-39</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@johannes johannes]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/johannes">@johannes</a> wrote:</p>
          <blockquote>
              <p>I haven't experienced this, maybe a the compiler was aborted somehow while generating the xpatch.h.gch file, but leaving a corrupt/incomplete file. Virus scanners are also suspect, quarantining the compiler, do you run any?</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/38">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/38</link>
        <pubDate>Tue, 31 May 2016 23:02:19 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-38</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@philoop]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/philoop">@philoop</a> wrote:</p>
          <blockquote>
              <p>not really the 3 last times it had short message mingw32 error, sorry i didnt copied it, i will investigate further <br>its more like this </p>

<aside class="quote" data-post="5" data-topic="583"><div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="//community.axoloti.com/user_avatar/community.axoloti.com/mexakin/40/703_1.png" class="avatar">mexakin:</div>
<blockquote><p>internal error in mingw32_.................................................: Attempt to access invalid address.</p></blockquote></aside>

<p>not soo urgent i guess, next time i will monitor closer what i did.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/37">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/37</link>
        <pubDate>Tue, 31 May 2016 22:07:13 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-37</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@hellcore]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/hellcore">@hellcore</a> wrote:</p>
          <blockquote>
              <p>I had this a fair amount today while testing out some new objects I have been working on. I'll try and see if there is any pattern when I continue tomorrow.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/36">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/36</link>
        <pubDate>Tue, 31 May 2016 22:05:11 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-36</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@thetechnobear Mark Harris]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/thetechnobear">@thetechnobear</a> wrote:</p>
          <blockquote>
              <p>is the error still exactly the same as you had originally?</p>

<aside class="quote" data-post="14" data-topic="583"><div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="//community.axoloti.com/user_avatar/community.axoloti.com/philoop/40/1206_1.png" class="avatar">philoop:</div>
<blockquote>
<p>Win8.1 64bit java 8.65.....error first time:</p>
<p>Datum:         22.10.2015 18:44:58</p>
<p>Name des fehlerhaften Moduls: cc1plus.exe, Version: 0.0.0.0, Zeitstempel: 0x55772e0b<br>Ausnahmecode: 0xc0000005<br>Fehleroffset: 0x008bbe56<br>ID des fehlerhaften Prozesses: 0x1380<br>Startzeit der fehlerhaften Anwendung: 0x01d10ce8fb1fb4c1<br>Pfad der fehlerhaften Anwendung: c:\program files (x86)\axoloti_runtime\platform_win\bin..\lib\gcc\arm-none-eabi\4.9.3\cc1plus.exe<br>Pfad des fehlerhaften Moduls: c:\program files (x86)\axoloti_runtime\platform_win\bin..\lib\gcc\arm-none-eabi\4.9.3\cc1plus.exe<br>Berichtskennung: 3a6317d3-78dc-11e5-8332-448a5ba4fd59</p>
</blockquote></aside>

<p>if this happens again, rather than deleting the build directly, can you just try to delete the xpatch.h.gch file<br>and then try to go live, and see if this fixes it.</p>

<p>also can you confirm it does it with all patches e.g. even the tutorial patches.</p>

<p>the issue is, this is not an axoloti bug as such, its the compiler crashing... so we need to determine what it is thats causing the compiler to crash.</p>

<p>whats obviously odd, is that it appears to be working for you, for months at a time, then suddenly stops... <br>so something must change... Im guessing its not something as 'obvious' as immediately after you upgrade Axoloti, as you would notice this... so its something outside of axoloti. </p>

<p>are others getting this regularly?</p>

<p>seems odd, johannes doesnt seem to get it... as he uses windows most of the time. (I dont)</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/35">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/35</link>
        <pubDate>Tue, 31 May 2016 21:43:57 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-35</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@philoop]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/philoop">@philoop</a> wrote:</p>
          <blockquote>
              <aside class="quote" data-post="31" data-topic="583"><div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="//community.axoloti.com/user_avatar/community.axoloti.com/inaba/40/644_1.png" class="avatar">Inaba:</div>
<blockquote><p>i just experienced thesame issue, and i solved it by going to my documents&gt;axoloti&gt;build and delete everything in that folder <img src="/images/emoji/emoji_one/smile.png?v=2" title=":smile:" class="emoji" alt=":smile:"></p></blockquote></aside>

<p>4ourth time mingw32 error</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/34">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/34</link>
        <pubDate>Tue, 31 May 2016 20:07:56 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-34</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@philoop]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/philoop">@philoop</a> wrote:</p>
          <blockquote>
              <p>third time mingw error...sigh ....i wonder what the cause is....</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/33">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/33</link>
        <pubDate>Wed, 30 Mar 2016 19:23:05 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-33</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@philoop]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/philoop">@philoop</a> wrote:</p>
          <blockquote>
              <p>I had the Problem again, and i can confirm the solution works:smiley:</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/32">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/32</link>
        <pubDate>Mon, 18 Jan 2016 18:09:40 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-32</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@Inaba ramon]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/inaba">@Inaba</a> wrote:</p>
          <blockquote>
              <p>i just experienced thesame issue, and i solved it by going to my documents&gt;axoloti&gt;build and delete everything in that folder <img src="/images/emoji/emoji_one/smile.png?v=0" title=":smile:" class="emoji" alt=":smile:"></p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/31">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/31</link>
        <pubDate>Mon, 11 Jan 2016 18:16:38 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-31</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@mexakin stef]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/mexakin">@mexakin</a> wrote:</p>
          <blockquote>
              <p>Had the problem again, dopnt knwo what issue is causing this, BUT you are right, i deleted the installation 3 times, nothing changed i got the error again, but when deleting my documents/runtime..blbalbalbaa folder it does work again now.</p>

<p>Just wanted to say that it seems to be the solution <img src="/images/emoji/emoji_one/smile.png?v=0" title=":smile:" class="emoji" alt=":smile:"> or workaround</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/30">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/30</link>
        <pubDate>Tue, 01 Dec 2015 22:33:29 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-30</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@mtyas Matthew Tyas]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/mtyas">@mtyas</a> wrote:</p>
          <blockquote>
              <p>I've just had the same problem (win 8.1 x64) and resolved it by deleting the build folder in \Documents\axoloti folder.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/29">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/29</link>
        <pubDate>Wed, 25 Nov 2015 09:28:54 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-29</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@mexakin stef]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/mexakin">@mexakin</a> wrote:</p>
          <blockquote>
              <p>Hi and thanks philoop for also stepping in and telling your problems.<br>I am now home again and simply did try another reinstall again, it does go live now here again.</p>

<p>What I did different: I got 2 partinions on my one laltop harddrive C and D, I do install axoloti on my C program files, but this time i did install the runtime on the D partition and it did work.</p>

<p>Just for further info:</p>

<p>My windows is: Win 7 Professional Service Pack 1</p>

<p>Java and stuff  I am right now not sure where to find, but if this is really important to you <img src="/images/emoji/emoji_one/smile.png?v=0" title=":smile:" class="emoji" alt=":smile:"> just say a word and I willl look it up.</p>

<p>Thanks for your kindly support, so now I am trying the midi clock stuff and get back with results.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/28">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/28</link>
        <pubDate>Sun, 25 Oct 2015 13:43:58 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-28</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
      <item>
        <title>Error when going live with the patching</title>
        <dc:creator><![CDATA[@philoop]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/philoop">@philoop</a> wrote:</p>
          <blockquote>
              <p>I also reinstalled the runtime but that didnt work.<br>Zonealarm had  blocked arm-none-eabi  but after fixing this  it still wasnt working.<br>Only a fresh install of the editor helped.<br>I didnt restart windows the first time I reinstalled.....</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/27">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583/27</link>
        <pubDate>Fri, 23 Oct 2015 18:09:52 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-583-27</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/error-when-going-live-with-the-patching/583.rss">Error when going live with the patching</source>
      </item>
  </channel>
</rss>
